
name: Partners Report
on:
  workflow_dispatch:
  schedule:
    # Wait for 1 hour of block history in the new month before starting export.
    - cron: 0 1 1 * *

jobs:
  run_partners_dot_py:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: [ mainnet ]
        include:
        # Providers for all chains.
        - network: mainnet
          label: ETH
          provider: WEB3_PROVIDER
      fail-fast: false

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python (faster than using Python container)
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
        
      - name: Prep dependencies
        run: pip install wheel && pip install "Cython<3.0" "pyyaml==5.4.1" --no-build-isolation

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Setup brownie networks
        run: brownie networks modify ${{ matrix.network }} host=${{ secrets[matrix.provider] }}

      - name: Partners Summary
        env:
          # Explorer tokens for all chains :
          ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
        run: brownie run partners_summary --network ${{ matrix.network }}
